sudo: required
services:
  - docker

before_install:
  - docker build -t gabrielchong1994/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gabrielchong1994/react-test npm test

after_success:
  - docker build -t gabrielchong1994/multi-client ./client
  - docker build -t gabrielchong1994/multi-nginx ./nginx
  - docker build -t gabrielchong1994/multi-server ./server
  - docker build -t gabrielchong1994/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  #Take those images and push them to docker hub
  - docker push gabrielchong1994/multi-client
  - docker push gabrielchong1994/multi-nginx
  - docker push gabrielchong1994/multi-server
  - docker push gabrielchong1994/multi-worker


